REGISTER_URL="https://tobeto.com/kayit-ol"
EPOSTA_WARNING_XPATH="//p[contains(.,'Geçersiz e-posta adresi*')]"
EPOSTA_TEXT_BOX_XPATH="//input[@name=\'email\']"
FALSE_EPOSTA="elif"
EPOSTA_WARNING_MESSAGE="Geçersiz e-posta adresi*"
VALID_EPOSTA="elifisci1103@gmail.com"
EPOSTA_WARNING_MESSAGE2_XPATH="xpath=//p[contains(.,'Doldurulması zorunlu alan*')]"
EPOSTA_WARNING_MESSAGE2="Doldurulması zorunlu alan*"
NAME_TEXT_BOX_XPATH="//input[@name=\'firstName\']"
LAST_NAME_TEXT_BOX_XPATH ="//input[@name=\'lastName\']"
EPOSTA_TEXT_BOX_XPATH="//input[@name=\'email\']"
PASSWORD_TEXT_BOX_XPATH="//input[@name=\'password\']"
REGISTER_BUTTON_XPATH="//button[@class='btn btn-primary w-100 mt-6']"
PASSWORD_AGAIN_TEXT_BOX_NAME="passwordAgain"
REGISTER_NAME="esra"
REGISTER_LAST_NAME="KAYA"
REGISTER_EPOSTA="elifisleyen743@gmail.com"
REGISTER_PASSWORD="1234567"
REGISTER_TEXT="Kayıt oluşturmak için gerekli sözleşmeler"
REGISTER_TEXT_XPATH = "//p[contains(.,\'Kayıt oluşturmak için gerekli sözleşmeler\')]"
